version: '3.8'

services:
  aios-api-proxy:
    build: .
    container_name: aios-api-proxy
    ports:
      - "8000:8000"
    environment:
      - LM_STUDIO_URL=http://host.docker.internal:1234
      - API_TIMEOUT=30
    restart: unless-stopped
    networks:
      - aios-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  aios-network:
    driver: bridge
